### ISSUE TITLE
Dockerfile for hyperglass?

### ISSUE THREAD

**Issue by zimage** [checktheroads/hyperglass#1]
Any interest in Dockerizing this app? I can do a pull request to add a Dockerfile.

**Comment by checktheroads** [comment]
> Any interest in Dockerizing this app? I can do a pull request to add a Dockerfile.

Go for it! Docker is something I’ve barely dabbled with, but would be very interested to learn more as well as see hyperglass made more accessible.

**Comment by checktheroads** [comment]
@zimage I'm closing out this Issue, consider the request approved and submit a PR at your convenience. Thanks!
