### ISSUE TITLE
Support arista_eos

### ISSUE THREAD

**Issue by spencerryan** [checktheroads/hyperglass#10]
Hello,

It looks like Arista devices are well supported/tested by Netmiko (device type arista_eos). 

Any chance we can get this support added? I've got a few EOS route reflectors that would be awesome if I could get them into hyperglass.

Thank you,

**Comment by checktheroads** [comment]
Hello! Any Netmiko supported OS should work, you would just need to add the relevant commands for that EOS to the `commands.toml` file, see [here](https://hyperglass.readthedocs.io/en/latest/installation/configuration/#commands). The built in OSs are just the ones have access to for testing, but if you find some good commands for EOS I’d be happy to add them or accept a PR to add them to the `commands.toml.example` file and docs.

**Comment by spencerryan** [comment]
I didn't even think of trying it, I assumed (incorrectly) you were only allowing the list of devices you claimed to be supported. It works fine!

I'll close this issue, give me a bit and I'll put a PR up for commands.toml.example. I've got a small army of Arista here here that's all dual stacked so I should be able to get a decent example config for you.

Thanks!

**Comment by checktheroads** [comment]
Fantastic, thanks!
