### ISSUE TITLE
Wrong result panel expanded

### ISSUE THREAD

**Issue by sciuridae0603** [checktheroads/hyperglass#100]
# Bug Description

This bug happened in click a loaded result below loading result , then it expand wrong result.

# Expected behavior

Show the correct result.

# Steps to Reproduce

- 1. Do a multi server query.
- 2. Click the result below loading result.

[Video](https://streamable.com/okaocr)

## Server

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.69** |
| **hyperglass Path** | `/etc/hyperglass` |
| **Python Version** | `3.8.5` |
| **Platform Info** | `Linux-5.4.78-2-pve-x86_64-with-glibc2.29` |
| **CPU Info** | Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz |
| **Logical Cores** | `16` |
| **Physical Cores** | `12` |
| **Processor Speed** | 2.8003106874999992GHz |
| **Total Memory** | 1.59 GB |
| **Memory Utilization** | 50.5% |
| **Total Disk Space** | 10.5 GB |
| **Disk Utilization** | 32.4% |

## Client

- OS & Version: Window 10
- Browser: Chrome , Firefox

**Comment by checktheroads** [comment]
I'll look into this. While I can reproduce it _exactly_, I can reproduce some similar weirdness, and I believe I know the cause.
