### ISSUE TITLE
Hyperglass ignoring cipher list

### ISSUE THREAD

**Issue by astlaurent** [checktheroads/hyperglass#108]
Hi

I am having a problem where hyperglass is not connecting to my ASR devices. I am getting

KeyExchangeFailed: No matching encryption algorithm found, sent chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr and received
aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc

You mentioned before that scrapli should be using the ssh config file however i do not think it is with the way it is implemented. I can connect out to the devices manually via ssh and ssh -Q cipher shows the appropriate ciphers in the list. The other odd item is it seems that hyperglass is only using the last 6 which i assume is because they are the strongest

ssh -Q cipher
3des-cbc
blowfish-cbc
cast128-cbc
arcfour
arcfour128
arcfour256
aes128-cbc
aes192-cbc
aes256-cbc
rijndael-cbc@lysator.liu.se
aes128-ctr
aes192-ctr
aes256-ctr
aes128-gcm@openssh.com
aes256-gcm@openssh.com
chacha20-poly1305@openssh.com

**Comment by checktheroads** [comment]
Hey @astlaurent - give v1.0.0-beta.74 a try. Previously, the Scrapli driver was specifically configured _not_ to use the system SSH config file. In v1.0.0-beta.74, I've removed this. It's a bit difficult to test, so let me know if this has any effect.

**Comment by astlaurent** [comment]
hey, sorry i just got around tp upgrading and i am still seeing cipher issues when connecting through hyperglass only
