### ISSUE TITLE
JSON Parse Unexpected Character At Line 1 Column 1 Of The JSON Data

### ISSUE THREAD

**Issue by MrFloffy** [checktheroads/hyperglass#113]
When i try to get queries through reverse proxy i get this error: 
JSON Parse Unexpected Character At Line 1 Column 1 Of The JSON Data.

I think i have an error in location line on the reverse proxy config but i'm not sure.

# Bug Description

When i try to get queries through reverse proxy i get this error: 
JSON Parse Unexpected Character At Line 1 Column 1 Of The JSON Data.

I don't get this error without reverse proxy.

# Expected behavior

Be able to get queries with reverse proxy without errors

## Local Configurations

```
server {
  listen 80;
  #listen [::]:80;
  server_name lg.mydomain.com;
  return 301 https://$host$request_uri;
}
server {
  #listen [::]:443 ssl ipv6only=on;
  listen 443 ssl;
  #ssl on;

  ssl_certificate       /etc/letsencrypt/live/lg.mydomain.com/fullchain.pem;
  ssl_certificate_key   /etc/letsencrypt/live/lg.mydomain.com/privkey.pem;

  client_max_body_size 5M;

  server_name lg.mydomain.com;

  root /etc/hyperglass/static;

  location / {
    try_files $uri $uri/ /ui /ui/$uri =404;
    index /ui/index.html;
  }

  location /openapi.json {
      try_files $uri @proxy_to_app;
  }

  location /custom/ {
      try_files $uri $uri/ /custom;
  }

  location /images/ {
      try_files $uri $uri/ /images;
  }

  location /api {
      try_files $uri @proxy_to_app;
  }

  location @proxy_to_app {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://[::1]:8001;
  }

}
```

## Logs
```
JSON Parse Unexpected Character At Line 1 Column 1 Of The JSON Data.
```

# Environment

## Server

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.75** |
| **hyperglass Path** | `/etc/hyperglass` |
| **Python Version** | `3.6.9` |
| **Platform Info** | `Linux-4.15.0-135-generic-x86_64-with-Ubuntu-18.04-bionic` |
| **CPU Info** | Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz |
| **Logical Cores** | `8` |
| **Physical Cores** | `8` |
| **Processor Speed** | 2.2GHz |
| **Total Memory** | 8.36 GB |
| **Memory Utilization** | 11.3% |
| **Total Disk Space** | 19.94 GB |
| **Disk Utilization** | 44.3% |

**Comment by checktheroads** [comment]
Hey,

Looks to me like you've disabled the IPv6 listen statements, but left the IPv6 localhost on the reverse proxy. I believe what you need to do is change line 48 to:

```nginx
proxy_pass http://127.0.0.1:8001;
```

That is, assuming you've also set the `listen_address` parameter to `127.0.0.1`.

**Comment by MrFloffy** [comment]
That's right, i feel like a fool. Thanks!! It's fixed.
