### ISSUE TITLE
Routing table name on the results page

### ISSUE THREAD

**Issue by hackybrittle** [checktheroads/hyperglass#119]
# Bug Description

The routing table name on the results page is displaying the same router name for all routers.

# Expected behavior
The name to be displayed there is the VRF name

# Environment

## Server
| **hyperglass Version** | **1.0.0-beta.73** |
| **Python Version** | `3.7.3` |
| **Platform Info** | `Linux-4.19.0-14-amd64-x86_64-with-debian-10.8` |

**Comment by checktheroads** [comment]
@hackybrittle — is this still an issue for you? I am unable to reproduce it.
