### ISSUE TITLE
Telnet support

### ISSUE THREAD

**Issue by diaafares** [checktheroads/hyperglass#12]
First let me thank you very much for you hard work on this awesome project, I'm a PHP guy and I was looking for the best Looking Glass solution and found some PHP solutions, but when I found your project I felt that it the right choice and the best by far!

I have three question I will be glad if I found their answers:

1. Does Hyperglass have the support of Telnet connection to routers? I need this feature very much, and found that [respawner/looking-glass](https://github.com/respawner/looking-glass) support it, but I like Hyperglass more than it, If Hyperglass will not support it, does it easy to implement Telnet feature or you have any plans to implement it?
2. In the Routers list, Can I show the location of group of Routers like other Looking Glass solution do, For example: North America, Asia 
![Screen Shot 2019-08-15 at 2 38 24 PM](https://user-images.githubusercontent.com/1811607/63092503-9e03d280-bf6a-11e9-80a7-ca707ed3e26b.png)

3. Can you tell me please when v1 will be released?

**Comment by checktheroads** [comment]
Thanks for the kind words! Answers below:

- hyperglass should support whatever Netmiko supports. Some quick googling suggests Kirk added a `_telnet` modifier to the device type names, but you may want to test this out, as I’ve never tried this.

- Coming in 1.0. Already built and works great. 

- Oof, hard to say. I’ve got a handful of features left to finish implementing before I’m ready to release it. The ole day job has been very demanding lately so I haven’t had much time to work on it. That said, I’m taking next week off for a mental health break, and I’m planning on dedicating some serious time to finishing up 1.0. I _hope_ I can finish up by end of week, but we’ll see.

**Comment by diaafares** [comment]
@checktheroads `_telnet` modifier work with me, thank you very much and please take care of yourself and take some breaks, that's will be better for your health recovery.

Lastly, I have some ideas I want to share with you, I will be very grateful if we can chat on Telgram or Skype or any other chatting app.

**Comment by checktheroads** [comment]
So telnet worked then? If so I will make sure to add that to the docs with the v1 release. For questions/chats - feel free to join us on Keybase! Link to the public team channel is in the readme.
