### ISSUE TITLE
Transparent Location Menu on Light Theme

### ISSUE THREAD

**Issue by Phobeus1** [checktheroads/hyperglass#121]
# Bug Description
On the most recent beta version, v1.0.0-beta.79, the Location menu drop down is now transparent instead of opaque. This issue is not apparent on the Dark Theme. This leads to the Light theme drop down menu items interfering with the target menu and causing confusion. 

![Light_Theme](https://user-images.githubusercontent.com/22281540/109556530-efb87300-7aa4-11eb-8c8e-d7976e457326.png)

![Dark_Theme](https://user-images.githubusercontent.com/22281540/109556647-18406d00-7aa5-11eb-83c9-5432e9c934d7.png)

# Expected behavior
Opaque Drop Downs on both Light and Dark Themes. 

# Steps to Reproduce
Update from v1.0.0-beta.78 to v1.0.0-beta.79 and access the location menu drop downs on WebUI.

# Environment

## Server

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.79** |
| **hyperglass Path** | `None` |
| **Python Version** | `3.8.6` |
| **Platform Info** | `Linux-5.8.0-44-generic-x86_64-with-glibc2.32` |
| **CPU Info** | Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz |
| **Logical Cores** | `6` |
| **Physical Cores** | `6` |
| **Processor Speed** | 2.199998GHz |
| **Total Memory** | 4.12 GB |
| **Memory Utilization** | 18.9% |
| **Total Disk Space** | 25.76 GB |
| **Disk Utilization** | 37.4% |

## Client

- OS & Version: Windows 10
- Browser: FireFox, Chrome, MS Edge

### Smartphone Details (if applicable)

- OS: Android 11
- Browser: Chrome

**Comment by checktheroads** [comment]
Thanks for submitting this - I will get it fixed in the next release!
