### ISSUE TITLE
cipher list in hyperglass still an issue

### ISSUE THREAD

**Issue by astlaurent** [checktheroads/hyperglass#122]
in reference to https://github.com/checktheroads/hyperglass/issues/108

I just recently had a chance to upgrade and it is still a issue on .79

**Comment by checktheroads** [comment]
Ok, thanks. Remind me - this issue occurs with your IOS-XR devices, correct? I apologize if you've already answered this, but are there any "non-default" SSH-related settings on those routers that I can add to my virtual XR appliance to reproduce? Also, what version of IOS-XR?

Thanks!

**Comment by carlmontanari** [comment]
👋 feel free to open an issue over in scrapli if we dont want to spam things here! 

looking at the other issue we can def test by "manually" passing kex/ciphers via the `transport_options` argument ([docs](https://carlmontanari.github.io/scrapli/user_guide/advanced_usage/#transport-options) and [example](https://github.com/carlmontanari/scrapli/blob/master/examples/transport_options/system_ssh_args.py)), also could quickly test t out w/ paramiko/ssh2 transports to see if everything else is working just to narrow down the scope of troubleshooting! 

if your ssh config file is not in one of the "normal" spots you'll need to pass the path as a string to `ssh_config_file` -- if you just pass `True` it will look for `~/.ssh/config` and `/etc/ssh/ssh_config`. of course you'll need to have the right ciphers/kex in the config file as well!

carl

**Comment by checktheroads** [comment]
@astlaurent - can you test this on v1.0.0-beta.82 (available shortly, pending CI build completion)? If it doesn't work out of the box on 82, try setting the new option on the device `driver: netmiko` - while not ideal, it's a sledgehammer approach to at least rule out differences in drivers.

**Comment by bile0026** [comment]
Also seem to have the same issue on MikroTik Devices if that helps. I have a key manually specified in devices.yaml that lives in the /etc/hyperglass folder for now. 

```
[CRITICAL] 20210425 02:55:04 | hyperglass.exceptions:40 | __init__ → [DANGER] Error connecting to RB4011: Request timed out.
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 73, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 359, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 364, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 339, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/execution/main.py", line 34, in handler
    raise DeviceTimeout(**exc_args)
hyperglass.exceptions.DeviceTimeout: Error connecting to RB4011: Request timed out.
```
```
| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.81** |
| **hyperglass Path** | `None` |
| **Python Version** | `3.8.5` |
| **Platform Info** | `Linux-5.4.0-72-generic-x86_64-with-glibc2.29` |
| **CPU Info** | Common KVM processor |
| **Logical Cores** | `4` |
| **Physical Cores** | `4` |
| **Processor Speed** | 2.659998GHz |
| **Total Memory** | 8.35 GB |
| **Memory Utilization** | 8.9% |
| **Total Disk Space** | 21.0 GB |
| **Disk Utilization** | 39.4% |
```

I  can also try .82 once it's out.

**Comment by bile0026** [comment]
Same issue on .82, and also tried setting driver to netmiko. Same error.

**Comment by checktheroads** [comment]
@bile0026 - so, just to be clear, you saw the same issue that @astlaurent had prior to beta82, but you no longer have the issue on beta82? @astlaurent - have you had a chance to test this out? This seemed kinda specific to IOS-XR, even down to specific versions of XR, so I'd like to make sure it's truly resolved before closing.

**Comment by bile0026** [comment]
> @bile0026 - so, just to be clear, you saw the same issue that @astlaurent had prior to beta82, but you no longer have the issue on beta82? @astlaurent - have you had a chance to test this out? This seemed kinda specific to IOS-XR, even down to specific versions of XR, so I'd like to make sure it's truly resolved before closing.

That is correct, issue went away after beta82. I tested on MikroTik though, not IOS-XR.
