### ISSUE TITLE
devices.yaml - multiple Juniper devices bug

### ISSUE THREAD

**Issue by erickhuge** [checktheroads/hyperglass#125]
Dears,

I'm trying to set-up the devices.yaml to connect with multiple PoPs using Juniper MX Routers, however, the first device works well, but in the second I see the netmiko are using something like Cisco syntax.

cat devices.yaml
routers:
  #Miami
  - name: Miami, FL
    address: miamiip
    network:
      name: miamifl
      display_name: AS65535
    credential:
      username: user1
      password: pass1
    port: 22
    nos: juniper_junos
    vrfs:
      - name: global
        default: true
        ipv4:
          source_address: 192.0.2.1
        ipv6:
          source_address: 2001:db8::1
    proxy: null
  #Sao Paulo
  - name: São Paulo, BR
    address: saopaulobr
    network:
      name: saopaulobr
      display_name: AS65535
    credential:
      username: user2
      password: pass2
    port: 22
    nos: juniper_junos
    vrfs:
      - name: global
        default: true
        ipv4:
          source_address: 192.0.2.1
        ipv6:
          source_address: 2001:db8::1
    proxy: null

[INFO] 20210305 19:23:33 | scrapli.driver.async_driver:100 | open → Opening connection to saopaulobr
[INFO] 20210305 19:23:35 | scrapli.driver.base_network_driver:318 | _pre_acquire_priv → Attempting to acquire `exec` privilege level
[INFO] 20210305 19:23:35 | scrapli.driver.base_network_driver:355 | _process_acquire_priv → Acquired requested privilege level `exec`

In the first router, same model and version, works fine. In the second, we'see a cisco syntax but without response.

**Comment by erickhuge** [comment]
Hello,

After some tests, we found a issue between Junos 18.2R3.4 and Scrapli.

Solved the problem when used version v0 and using Netmiko.

**Comment by checktheroads** [comment]
Hello,

Sorry for the delay, I was traveling for work and then took some extra time off afterward, but now I'm starting to catch up!

I'm having trouble understanding and reproducing this. I have two Juniper routers in my day job's production network, MX204s, one on 18.2R3.4, the other on 19.4.R3.11, and I'm able to query both from hyperglass just fine. The _only_ difference I see in your configuration vs. mine is that you're using `juniper_junos` as the NOS, and I'm using `juniper`. However, this shouldn't matter as `juniper_junos` gets remapped automatically to `juniper` [here](https://github.com/checktheroads/hyperglass/blob/571d2368715950abd0abb95102c11d3e836d611f/hyperglass/constants.py#L70).

Do you see any different behavior if you set yours to just `juniper`? Do you see this issue if you only have one router defined, or does it only happen when you have more than one?

You mention seeing Cisco syntax - can you elaborate? If you're referring to the `Attempting to acquire exec privilege level` message, I believe this is a normal Scrapli message that appears regardless of NOS (I see the same message in my working Juniper logs).

**Comment by erickhuge** [comment]
Hello,

Same behavior even if I set to "juniper" or "juniper_junos".

In my test, I have two Routers (one in Miami - and one in Sao Paulo (BR), same model)

Miami node works fine, Sao Paulo don't work, even if are applied if this router is the only defined in the devices.yaml.

Attached one log for Sao Paulo, and one log file for Miami.

INFO: We're able to connect to the "problem" router through SSH, same credentials, with same command.

SAO PAULO Firmware: 18.2R3.4
MIAMI Firmware: 18.2R3-S5.3

[miami.txt](https://github.com/checktheroads/hyperglass/files/6355152/miami.txt)

[saopaulo.txt](https://github.com/checktheroads/hyperglass/files/6355126/saopaulo.txt)

**Comment by checktheroads** [comment]
This is very odd, and I can't seem to reproduce or make sense of it. That said, v1.0.0-beta.82 — which should be available shortly — has upgraded almost all dependencies to their latest versions (Scrapli included). Can you give it a try? If that doesn't work, beta 82 also adds a new option on the device model that allows you to override the driver. For example, you could set `driver: netmiko` to force hyperglass to use Netmiko to connect to the devices instead of Scrapli. Could you try that as well and see if you see any difference?

**Comment by erickhuge** [comment]
Yeah, very odd... But I have good news: worked like a charm with "driver: netmiko" :-D

**Comment by checktheroads** [comment]
Hey, I'll take it!
