### ISSUE TITLE
Define unique commands per device

### ISSUE THREAD

**Issue by spencerryan** [checktheroads/hyperglass#13]
We'd love to use hyperglass for visibility into our lab networks, however those are all OSPF. 

The ability to override commands per device would be very useful, for example I can effectively just replace the bgp route commands with some form of `show ip ospf {target}` and get the output I want.

Right now we have a workaround by running a second HG instance and setting those OSPF commands but it would be great if we could integrate it all into one.

**Comment by checktheroads** [comment]
I think this is doable. It would probably take the form of another per-device field, wherein a "command profile" would be set, rather than referencing the Netmiko NOS name. I'll add this to my list of of things to do in 1.0!

**Comment by checktheroads** [comment]
Hello!

I can finally close this out, as this feature is live in the [v1.0.0 beta release](https://github.com/checktheroads/hyperglass/tree/v1.0.0). I'd love for you to give it a go and let me know of any feedback.
