### ISSUE TITLE
Build/Start Fails on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by bile0026** [checktheroads/hyperglass#136]
# Bug Description

Build failed with missing fonts using the install.hyperglass.io script. This same error also happens when trying to follow the installation instructions manually.

# Expected behavior

Should be able to start hyperglass once the script completes.

# Steps to Reproduce

1. Run the install.hyperglass.io automated install script.
2. run `hyperglass start` or `hyperglass build-ui`

## Local Configurations

```
<configs>
```

## Logs

```
Warn: Can't find .pfb for face 'Times-Roman'

Error: Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None

```

# Possible Solution

# Environment

## Server

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.81** |
| **hyperglass Path** | `None` |
| **Python Version** | `3.8.5` |
| **Platform Info** | `Linux-5.4.0-72-generic-x86_64-with-glibc2.29` |
| **CPU Info** | Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz |
| **Logical Cores** | `2` |
| **Physical Cores** | `2` |
| **Processor Speed** | 2.1948440000000002GHz |
| **Total Memory** | 8.35 GB |
| **Memory Utilization** | 13.8% |
| **Total Disk Space** | 63.14 GB |
| **Disk Utilization** | 74.2% |

## Client

- OS & Version: 
- Browser: 

### Smartphone Details (if applicable)

- Device: 
- OS: 
- Browser:

**Comment by zerosays** [comment]
Working well on my 20.04.2 LTS

**Comment by checktheroads** [comment]
Hello,

I don't think this is related to hyperglass. The CI testing that runs on before every release uses Ubuntu 20.04 with Python version 3.6 and 3.8 — if there was an issue with hyperglass and/or Ubuntu 20 compatibility, those tests would fail. After some limited googling, this seems like something is related to the system's python libraries (or lack thereof), occurring across various versions of Ubuntu and Debian. I'd suggest starting with a fresh Linux installation.

Thanks,
Matt
