### ISSUE TITLE
MK  SSL issue

### ISSUE THREAD

**Issue by zerosays** [checktheroads/hyperglass#138]
After **enabling SSL** with **Nginx**.. Can't seem to query/login to any of My **Mikrotik** Nodes. Error " **Bad Gateway**"

**Comment by checktheroads** [comment]
Can you share your Nginx configuration?

**Comment by zerosays** [comment]
`server {
  listen 80;
  listen [::]:80;
  server_name lg.domain.1 lg.domain.1;
  return 301 https://$host$request_uri;
}
server {
  listen [::]:443 ssl ipv6only=on;
  listen 443 ssl;
  ssl_certificate /******/fullchain.pem;
  ssl_certificate_key /*****/privkey.pem;

  client_max_body_size 2M;

  server_name lg.domain.1 lg.domain.2;

  root /etc/hyperglass/static;

  location / {
    try_files $uri $uri/ /ui /ui/$uri =404;
    index /ui/index.html;
  }

  location /openapi.json {
      try_files $uri @proxy_to_app;
  }

  location /custom/ {
      try_files $uri $uri/ /custom;
  }

  location /images/ {
      try_files $uri $uri/ /images;
  }

  location /api {
      try_files $uri @proxy_to_app;
  }

  location @proxy_to_app {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://[::1]:8001;
 }

}
`

**Comment by checktheroads** [comment]
Ok, that looks fine. How about your `hyperglass.yaml`? Bad Gateway generally means Nginx can't communicate with the back end, for whatever reason. Are you sure hyperglass is a) running, and b) listening on `[::1]:8001`?

**Comment by zerosays** [comment]
b) changed that to my v4 address 102.***:8001

I'll try v6 later on. Thanks @checktheroads
