### ISSUE TITLE
execute.py (intentionally) drops address families other than v4/v6 on IOS/IOS XR devices

### ISSUE THREAD

**Issue by spencerryan** [checktheroads/hyperglass#16]
I consider this to be a bug. Most of the routers that we use hyperglass for are Cisco devices that use VRFs, and thus the outputs for BGP community and AS_PATH show up under the VPNv4/6 Unicast family, and not IPv4/6 Unicast. 

I'm not entirely sure why you'd want to hide the other address families but there could be a valid reason I'm not thinking of.

To bypass this, I've changed lines 290/302 in `hyperglass/command/execute.py` to skip the call to self.parse (effectively making them `output = raw_output`) and now I happily get output from my IOS devices, and if that's the route you want to go it seems that the entire parse() function no longer has a purpose.

**Comment by checktheroads** [comment]
I'm closing this out, as full VRF support has been built into the [v1.0.0 beta release](https://github.com/checktheroads/hyperglass/tree/v1.0.0).
