### ISSUE TITLE
Add support for rfc8522

### ISSUE THREAD

**Issue by thegagne** [checktheroads/hyperglass#20]
**A little about you.**
I want looking glass data to be available via public APIs. How cool would that be?

**Is your feature request related to a problem? Please describe.**
Similar to your reasoning for building this project, I use looking glasses to find problems, but it stinks using all the junky web interfaces. I want to be able to use multiple looking glasses programmatically. 

**Describe the solution you'd like**
Implement https://tools.ietf.org/html/rfc8522

**Additional context**
Great work!

**Comment by checktheroads** [comment]
Hi @thegagne!

So I’m actually _extremely_ close to having this already in the imminent 1.0 release (available, barely tested, definitely broken with FRR/BIRD in the `v1.0.0` branch), scanning over the RFC the only thing missing might just be the data structure itself. But I’ve turned the entire app into a JSON API that just happens to have a pretty GUI. I will dig into this a some more and see if this is easy enough to roll into 1.0, or if it will require a little more work.

**Comment by checktheroads** [comment]
Well that was a pretty short read. The only thing that would require much actual work would be the addition of the `show route` spec in section 3.2.1. When building hyperglass I specifically chose not to include this option as I found it redundant and less useful than `show bgp`, but I suppose I could get over that. I’ll see what I can do on this.

**Comment by thegagne** [comment]
Sweet!

**Comment by checktheroads** [comment]
@thegagne - Quick update on this. As I'm finishing up the v1.0.0 release (yeah, "*extremely close*" is apparently one of those funny relevant terms), I took a stab at implementing this. As I read more closely into the RFC, I found that implementing this will require some pretty significant changes to how request data is ingested and validated. For example, the current (or rather, current in the v1.0.0 branch) way data is ingested is via an HTTP POST, with the request body containing a JSON structure of:

```js
{
    "query_location": "<router_name>",
    "query_type": "<bgp_route|bgp_aspath|bgp_community|ping|traceroute>",
    "query_target": "<ip|regex|community>",
    "query_vrf": "<vrf_name>"
}
```

However, the RFC calls for the data to be ingested via HTTP GET, with all the query details as HTTP query parameters in the URL (e.g. `http://lg.example.com/ping/192.0.2.1`, or as a more complicated example, `http://lg.example.com/show/bgp/summary?protocol=2&routerindex=3`.

While this is do-able, and I *will* do it, it's not as quick and easy as it might seem. Additionally, the RFC does **not** contain any models or specification for BGP AS_PATH or Community query types (or, functions, as the RFC calls them). So, I'm left to either add these on myself while taking a wild stab at how to standardize it, or have a completely separate query path for RFC8522-style queries (e.g., POST to `/api/query/` for "normal" queries, or for RFC8522 queries, use `/.well-known/looking-glass/{...}`), which I don't care for.

So, all that to say: I'm going to keep this issue open as I'd really like to add this as a feature, but I'm not going to be including it in v1.0.0. I did leave the code I started in the v1.0.0 branch (which will eventually merge to master), and will add on to it as I am able to.

Cheers!
-Matt

**Comment by thegagne** [comment]
Thanks for the update.

To be transparent, I don't really have any strong vested interest either way, other than I want access to more open looking glasses via API, and RFC8522 looked promising.

Do you not care for the path /.well-known/looking-glass, or just the fact that the API structure isn't compatible with what you've built so far and you don't want to split the design?

Maybe you could make some comments on the RFC if you think it could be improved.

**Comment by checktheroads** [comment]
Good to know!

Other than the lack of support for Community/AS Path, I don’t really have too many complaints about the spec. I don’t like the `.well-known/` URI, but I understand the intent. I assume the intent is to have a published base URL (like from PeeringDB, or perhaps a whois field), and have any supporting LG have a standard URI behind the base URL. I feel like that’s not really necessary, as you could simply make said field the full path to the API, e.g. `lg.domain.tld/api/whatever`, but that’s my opinion 😉

Commenting on the RFC is a good idea, perhaps after I integrate the Community/AS Path queries into the spec I can make those suggestions with real examples.

Btw - with 1.0.0 hyperglass will have full API support, in fact the UI is just a small React app that calls the API. I used [FastAPI](https://fastapi.tiangolo.com/), which automatically builds Swagger UI/Redoc API docs as well, so that’ll be cool.

**Comment by thegagne** [comment]
Yeah the path thing to me doesn't matter as much as long as there is a standard. I think /api is taken for a lot of other things (possibly a separate vendor specific API with other features), and not assumed to be available, while .well-known is a reserved path. That said, I think this would be the first api to use that, so it's not like there is a strong precedent.

**Comment by thegagne** [comment]
As an aside, another thing on my wishlist if/when there are more of these looking glasses is a way to find them and metadata about them. Is auth required? rate limits? contact info? A directory could work if someone maintained it, or maybe there could be a registration mechanism.

I could see something like this very useful for a network operator to find open LGs nearby when troubleshooting, or occasionally checking neighbors LG to see if things are good.

**Comment by checktheroads** [comment]
It looks like a few have tried:

- [bgplookingglass.com](http://www.bgplookingglass.com/)
- [lookingglass.org](https://lookinglass.org/sorted.php)
- [bgp4.as](https://www.bgp4.as/looking-glasses)

But I don’t see any way of submitting a new LG to any of them, nor do they contain all the information you just mentioned. Honestly, this isn’t hard - it could be as easy as a GitHub repo with flat Markdown files. Anyone could submit their AS via a Pull Request, maintainers could do some quick verification of the PR prior to merging.

I like the idea! I could see getting “fancy” with it and storing the data in YAML/JSON, and add a simple static web app (Hugo, Docusaurus) that builds in a GitHub Action.

You’ve got me thinking...

**Comment by thegagne** [comment]
Some more random ideas that I don’t have time to really explore:

0. Assuming public routers have http://IP/.well-known/ routes
1. A central registration or method of discovery.
2. A queryable DB of the above to find relevant lg
3. A way to setup api calls that I care about on a cron basis.
4. A visualizer/diff tool of the historical calls.
5. Alerts, reports, etc

**Comment by checktheroads** [comment]
I'm closing this out now, as v1.0.0 has support for _almost_ all of RFC8522 (and then some), or least as much as I'm willing to implement for now.
