### ISSUE TITLE
Quagga Support

### ISSUE THREAD

**Issue by kotuk** [checktheroads/hyperglass#24]
Can you add support for quagga

**Comment by checktheroads** [comment]
Have you seen [hyperglass-frr](https://github.com/checktheroads/hyperglass-frr)? It does not directly support Quagga, but it‘s really just a REST API wrapper around `vtysh` and Linux ping/traceroute commands, so I’m fairly certain it would work. Can you give it a go and let me know if something doesn’t work?

I’m open to implementing something minor if it’s missing to specifically support Quagga, as long as it doesn’t break support for FRR. But, seeing as how Quagga isn’t really actively developed anymore, I don’t want to put a bunch of effort into supporting it unless there’s massive community demand.

Anyway, I’m going to close this issue for now; if you try hyperglass-frr and it doesn’t work with Quagga, please raise an issue with the specifics and I’ll see what I can do.

Thanks!
-Matt
