### ISSUE TITLE
peering db link no longer works

### ISSUE THREAD

**Issue by astlaurent** [checktheroads/hyperglass#33]
noticed that the peering db link no longer works. https://www.peeringdb.com/AS# no longer brings up the AS information. I think peering DB might have changed something?

**Comment by checktheroads** [comment]
Is this in v1? If so, which specific version (`hyperglass —version`)? Another user caught this early on after I made v1 available, and it was fixed shortly thereafter. The new URL scheme is `https://www.peeringdb.com/asn/{asn}` - code [here](https://github.com/checktheroads/hyperglass/blob/1c9aee460881207e323f72a5c0d17db88e1ecc8d/hyperglass/configuration/models/web.py#L79).

However, I do see that the [docs](https://hyperglass.io/docs/ui#external_link) show the old scheme in the default value, I’ll get that fixed. Ultimately, you can make the URL whatever you want - it doesn’t have to be PeeringDB.

**Comment by astlaurent** [comment]
I am using the latest version build up think it is  25. I will check the config as I brought it over from a earlier v1 version so maybe it is messed up in that. More than likely I can make the adjustment there

**Comment by checktheroads** [comment]
Ah - yes, it used to be configured as a specific PeeringDB field, but I changed this to be a more generic URL so one could link to a website, peering policy, or something like that. Sorry about that. During this beta stage I'm not really documenting or communicating some of the "minor" breaking changes. Let me know if you're able to get this worked out or if you still see an issue. Thanks!

**Comment by astlaurent** [comment]
you were right. the config file i had was older, i confirmed against the original example file and it is different in that section. I fixed up my copy and it works well. 

Thanks
