### ISSUE TITLE
Version 1.0.0 is not working with FRR anymore

### ISSUE THREAD

**Issue by netfreak98** [checktheroads/hyperglass#39]
The new version of hyperglass isn't working with the hyperglass_frr API anymore. Is there also a new API version available to use?

**Comment by checktheroads** [comment]
Hey there, yes, now there's [hyperglass-agent](https://github.com/checktheroads/hyperglass-agent) which covers support for FRR & BIRD. (Some) docs [here](https://hyperglass.io/docs/agent/installation). I still have some to-dos when it comes to cleaning up the hyperglass-agent installation process (and docs), so if you run into any issues let me know via [Gitter](https://gitter.im/hyperglass).

Thanks!

**Comment by netfreak98** [comment]
hey :)

thanks. It's still not working :P
After doing:

pip3 install --user hyperglass-agent

The command "hyperglass-agent setup" is not available.

Was trying to find some docs but the link to the documentation is broken:
https://github.com/checktheroads/hyperglass-agent

Best regards,
Joey

**Comment by checktheroads** [comment]
You might have to run `source .profile` (or log out and back in) - I've noticed pip doesn't always refresh the `$PATH`. Sorry about the dead link in the docs - it should go to https://hyperglass.io/docs/agent/installation as I don't currently have a "main" page at https://hyperglass.io/docs/agent

**Comment by netfreak98** [comment]
Perfect, that helped :)
