### ISSUE TITLE
Mikrotik Routeros/Switchos Unsupported

### ISSUE THREAD

**Issue by zerosays** [checktheroads/hyperglass#41]
Getting that even after changing the Nos Key.
 File "/usr/local/lib/python3.6/dist-packages/hyperglass/configuration/models/routers.py", line 73, in supported_nos
    raise UnsupportedDevice('NOS "{n}" is not supported.', n=value)
hyperglass.exceptions.UnsupportedDevice: NOS "mikrotik_switchos" is not supported.

**Comment by checktheroads** [comment]
Hi there,

Looks like Mikrotik support was added by Netmiko in [2.4.0](https://github.com/ktbyers/netmiko/releases/tag/v2.4.0), and we're using 2.4.2 in the v1.0.0 branch, so we should be good. However, I do see that the list of network operating system in the hyperglass validation code is not up to date, which is why you're seeing this error. I'll get this corrected in the next v1.0.0 beta release.

**Comment by zerosays** [comment]
Thanks mate.

When should we expect the release? Routeros is our core :100:

**Comment by checktheroads** [comment]
Well, you caught me in the middle of a minor refactor, which I admittedly haven't touched in a couple weeks due to scheduling. I believe I just need to review a few items to make sure I didn't break anything, and I can push a new version up. I'll try to get this done today, if not tomorrow.

**Comment by zerosays** [comment]
Aight..

Will be waiting. Thanks Much @checktheroads

**Comment by zerosays** [comment]
Any update @checktheroads ?

**Comment by checktheroads** [comment]
Should be all set with 1.0.0-beta32. Let me know if you have any troubles.

Thanks,
Matt

**Comment by zerosays** [comment]
", line 133, in scrape
    command = attrgetter(".".join(cmd_paths))(commands)
AttributeError: 'Commands' object has no attribute 'mikrotik_switchos'

**Comment by checktheroads** [comment]
There are no predefined Mikrotik commands, you'll have to define your own since we don't have built-in support for Mikrotik. See [here](https://hyperglass.io/docs/commands) for more details. I'm also adding something to my todo list to make this error more helpful.

**Comment by zerosays** [comment]
Cant figure out what to place on the "ipv4_default"

**Comment by zerosays** [comment]
[INFO] 20200530 03:10:58 | hyperglass.api.routes:59 | query → Starting query execution for query Query(query_location=sfo_router01, query_type=traceroute, query_vrf=customer_a, query_target=8.8.8.8)
[ERROR] 20200530 03:10:58 | hyperglass.execution.execute:253 | scrape_direct → Connection to device timed-out: mikrotik_routeros ***** :2221
[CRITICAL] 20200530 03:10:58 | hyperglass.exceptions:28 | __init__ → [DANGER] Error connecting to ****** : Request timed out.

**Comment by checktheroads** [comment]
What custom command did you define for traceroute? On a mikrotik, traceroute is more like MTR, particularly in the way it never actually ends unless you specify a timeout. I don’t recall off the top of my head what those commands/options are, but ultimately, you need to have it run the traceroute with specific parameters. It might help to look at the [defaults](https://github.com/checktheroads/hyperglass/blob/v1.0.0/hyperglass/configuration/models/commands/cisco_ios.py) for the other NOS with built in support to get an idea of which options to set.

**Comment by zerosays** [comment]
Hi Matt,
Here's and example of an exc from a mk's cli:

[admin@wofbit_den] > tool traceroute 8.8.8.8
 # ADDRESS                          LOSS SENT    LAST     AVG    BEST
 1 102.68.141.25                      0%    4   2.9ms     2.7     1.7
 2 102.68.141.9                       0%    4   2.2ms     2.3     1.4
 3 102.68.141.5                       0%    4   3.5ms     2.7     2.1
 4 184.104.203.241                    0%    4   2.3ms     2.6     1.6
 5 184.105.64.210                     0%    4  63.5ms    62.3    61.2
 6 196.223.14.41                      0%    4  63.1ms    63.4    63.1
 7 74.125.245.193                     0%    4  61.3ms    61.1    60.6
 8 172.253.66.1                       0%    3  63.3ms    62.7    61.5
 9 8.8.8.8                            0%    3  60.7ms    60.9    60.7

**Comment by checktheroads** [comment]
Try this: 

```
tool traceroute timeout=1 duration=5 {target}
```

**Comment by zerosays** [comment]
[SUCCESS] 20200530 05:57:08 | hyperglass.api.routes:114 | query → Completed query execution for Query(query_location=sfo_router01, query_type=traceroute, query_vrf=default, query_target=8.8.8.8)

Got that with no login log from the mikrotik. Tried several devices; No login logs.

**Comment by checktheroads** [comment]
1.0.0-beta.33 should fix this, however, in my testing, ktbyers/netmiko#1600 seems to make the support for mikrotik less than ideal. I noticed while running traceroute commands, that part of the command comes back in the response (twice), and when running a ping command, we only get one ping back before the session is disconnected. I wasn't able to test any BGP commands as I don't have BGP on my home router (which is the mikrotik I'm testing with).

**Comment by zerosays** [comment]
Okay. Thanks for that. 
If necessary, Can create a tunnel for you to test the BGP commands.

When will the .33 be out?

**Comment by checktheroads** [comment]
It was out when I wrote the comment about it :) And no need on the tunnel - I have an EVE-NG setup at work I can use to set up some BGP with Mikrotiks.

**Comment by zerosays** [comment]
Okay

Waiting for the fix.

**Comment by zerosays** [comment]
Any update on this ?

**Comment by iamluca** [comment]
Has a solution been found?

**Comment by checktheroads** [comment]
I’ve not checked up on this in a little while, but I do see that @zerosays [commented](https://github.com/ktbyers/netmiko/issues/1600#issuecomment-670351126) on the issue and said that setting `global_cmd_verify': False` seems to fix the issue. I don’t currently expose the means to pass arguments directly to Netmiko, but if you're managing your own fork or want to test it out, you could add it [here](https://github.com/checktheroads/hyperglass/blob/1128d1f9020c8c425487b4f05af94da13abb8a6c/hyperglass/execution/drivers/ssh_netmiko.py#L53).

As a permanent solution, I may try writing a basic [Scrapli](https://github.com/carlmontanari/scrapli) driver for Mikrotik and see how that goes.

**Comment by checktheroads** [comment]
@zerosays @iamluca Mikrotik support is officially native as of 1.0.0-beta.59. I've done my best to work around the above Netmiko issue, but if you run into any weird looking output issues, let me know via a new issue.

Thanks!

**Comment by checktheroads** [comment]
@carlmontanari oh, nice! I didn't even know about the scrapli_community repo. I'll absolutely test this out and switch hyperglass over to it for Mikrotik devices.

**Comment by carlmontanari** [comment]
Yeah, sorry about that.... I've done poorly at "advertising" it, but happened to do a vanity search for "scrapli" and saw this so figured I'd chime in :D Holler here or slack or twitter or wherever if any scrapli related stuff comes up -- happy to help out!
