### ISSUE TITLE
Extended community problem

### ISSUE THREAD

**Issue by moguv587** [checktheroads/hyperglass#42]
For most routers,there are using type:administrator:assigned-number
when i input target:1:1, it shows "an invalid BGP Community."

**Comment by checktheroads** [comment]
Have you tried overriding the default BGP Community validation pattern to better suit your needs? Assuming you’re using v1, see [these docs](https://hyperglass.io/docs/queries#community-patterns). For v0/original/current master branch, see [here](https://hyperglass.readthedocs.io/en/latest/installation/features/#bgp-community).

**Comment by moguv587** [comment]
i missed that part,thanks
