### ISSUE TITLE
API timeout for FRR and BIRD insufficient

### ISSUE THREAD

**Issue by chriselsen** [checktheroads/hyperglass#43]
## Information

**Describe the bug**
With ping on FRR and BIRD using by default a count of 5 (-c 5) and no response timeout (-W), the resulting time it takes for a ping to an unavailable host is too short. As a result end-users see the message that "an error has occurred" instead of "Unable to reach x.x.x.x.".
Increasing the API call timeout to 15 seconds fixes this.

**To Reproduce**
Ping an unavailable host from an FRR or BIRD router. Response will be "an error occurred" due to the API timeout hitting before the ping on the router completes. 

**Expected behavior**
End-users should see the message "Unable to reach x.x.x.x." instead

**Screenshots**
N/A

### Back End
**Server:**
 - OS: Ubuntu 18.04
 - Python Version: Python 3.6.9
 - Reverse Proxy: Nginx
 - Redis Version: Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3

### Front End
**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version Windows 10

**Comment by checktheroads** [comment]
First, thanks for using the issue template 😉 Second, my issue template needs updating for this question - what version of hyperglass are you running? Namely just need to know if you’re using v1.0.0 (and specific beta version), or the “original” version from the master branch.

**Comment by checktheroads** [comment]
Never mind - I see now from your pull request that it’s the master branch version. I’ll look at this more closely shortly and probably merge. However, I would suggest migrating over to v1.0.0 as it will be merged to master soon.
