### ISSUE TITLE
Favicons are not displaying

### ISSUE THREAD

**Issue by chriselsen** [checktheroads/hyperglass#45]
## Information

**Describe the bug**
Favicons are not displaying. Neither standard ones, nor custom ones

**To Reproduce**
Deploy version 1.0.0-beta.40, check if favicons are included in HTML code for /

**Expected behavior**
HTML code for favicons should be included in HTML code for /

**Screenshots**
N/A

## Environment

Version: 1.0.0-beta.40

**Comment by checktheroads** [comment]
Yeah, I’m aware of this one, it’s on my list of things to build. I want to be able to take the icon and generate all the required formats automatically, and I haven’t tested out the JS library thy can supposedly do this, yet. Since this issue is opened now I’ll make it a higher priority.
