### ISSUE TITLE
Add support for arista eos

### ISSUE THREAD

**Issue by neldog2** [checktheroads/hyperglass#47]
Adding suggested feature request for support Arista's EOS.

vEOS is available at https://www.arista.com/en/support/software-download

**Comment by checktheroads** [comment]
Hi there, built-in EOS support is a part of [v1.0.0](https://github.com/checktheroads/hyperglass/tree/v1.0.0), which is currently in a stable but incomplete beta. I'm not planning on adding any new features to the "original" version, so if you're wanting to stay on that version, I'd suggest adding [custom commands](https://hyperglass.readthedocs.io/en/latest/installation/configuration/#commands) to support EOS. However, I would encourage you to migrate to v1 as that will be the the main version available, just as soon as I can finish up a few remaining features and documentation.

Thanks!
-Matt
