### ISSUE TITLE
BETA: Unable to build-ui, next build is failing

### ISSUE THREAD

**Issue by samip5** [checktheroads/hyperglass#50]
This is not starting quite well and also, PLEASE have a better error than that when using build-ui, and at least tell the user directly what command failed as I had to look pretty closely at your code to find the actual command which failed.

Version: 1.0.0b46
OS version: Ubuntu 20.04 LTS
Node version: 14.5.0

```
# hyperglass build-ui
[INFO] 20200702 17:48:25 | hyperglass.configuration:41 | <module> → Configuration directory: /etc/hyperglass
Starting new UI build...
[INFO] 20200702 17:48:33 | hyperglass.util:586 | build_frontend → Starting UI build...
❌ Error building UI:
Messages:
Creating an optimized production build...
Errors:
Killed
```

The ACTUAL error:
```
# node_modules/.bin/next build
> Build error occurred
Error: Cannot find module '/tmp/hyperglass_8gtbu01q.json'
Require stack:
- /usr/local/lib/python3.8/dist-packages/hyperglass/ui/next.config.js
- /usr/local/lib/python3.8/dist-packages/hyperglass/ui/node_modules/next/dist/next-server/server/config.js
- /usr/local/lib/python3.8/dist-packages/hyperglass/ui/node_modules/next/dist/build/index.js
- /usr/local/lib/python3.8/dist-packages/hyperglass/ui/node_modules/next/dist/cli/next-build.js
- /usr/local/lib/python3.8/dist-packages/hyperglass/ui/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/local/lib/python3.8/dist-packages/hyperglass/ui/next.config.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/python3.8/dist-packages/hyperglass/ui/next.config.js',
    '/usr/local/lib/python3.8/dist-packages/hyperglass/ui/node_modules/next/dist/next-server/server/config.js',
    '/usr/local/lib/python3.8/dist-packages/hyperglass/ui/node_modules/next/dist/build/index.js',
    '/usr/local/lib/python3.8/dist-packages/hyperglass/ui/node_modules/next/dist/cli/next-build.js',
    '/usr/local/lib/python3.8/dist-packages/hyperglass/ui/node_modules/next/dist/bin/next'
  ]
}
```

**Comment by checktheroads** [comment]
Unfortunately, an interface between Python and yarn/npm does not exist (ok, there is one out there, and it's just a `subprocess` wrapper that doesn't work very well), nor does yarn support parseable errors or IO redirection. So, the best I could come up with is printing any `stdout` messages under the `Messages:` block, and any `stderr` messages under the `Errors:` block as you see above. If you have any other ideas about how to improve this, I welcome them!

Regarding the error itself, are you still running this in an LXC container (from #49)? I should also note, I have done ZERO testing with hyperglass on Ubuntu 19 or 20. While I do know of one user that was successful with installing on 19, you're the first I've had try it with 20. Not to say that it shouldn't work, just that it hasn't been tested. I've also not tested with Python 3.8, although again, I don't see why that wouldn't work.

The error in your second block is unlikely to be the actual source of the problem - the `/tmp/hyperglass_<build id>.json` file is generated and destroyed during the build process by default, so running the `next build` command outside of a build won't work.

My process for troubleshooting such issues is to set the [`developer_mode`](https://hyperglass.io/docs/parameters#global-settings) key to `true`, then running `hyperglass build-ui`, and _then_ running `node_modules/.bin/next build` as you did above. This should persist the build file, which should get you past the "Cannot fine module" error and show the actual error that occurs during the build process. Can you try this, and let me know the result?

**Comment by samip5** [comment]
> Unfortunately, an interface between Python and yarn/npm does not exist (ok, there is one out there, and it's just a `subprocess` wrapper that doesn't work very well), nor does yarn support parseable errors or IO redirection. So, the best I could come up with is printing any `stdout` messages under the `Messages:` block, and any `stderr` messages under the `Errors:` block as you see above. If you have any other ideas about how to improve this, I welcome them!

Okey, so you're working with what you got. I got it, and from the top of my head, I have no clue. Off-Topic: Interfacing with C++ is even more interesting from Python.

> Regarding the error itself, are you still running this in an LXC container (from #49)? I should also note, I have done ZERO testing with hyperglass on Ubuntu 19 or 20. While I do know of one user that was successful with installing on 19, you're the first I've had try it with 20. Not to say that it shouldn't work, just that it hasn't been tested. I've also not tested with Python 3.8, although again, I don't see why that wouldn't work.

Yes, it's still the same LXC container.

> My process for troubleshooting such issues is to set the [`developer_mode`](https://hyperglass.io/docs/parameters#global-settings) key to `true`, then running `hyperglass build-ui`, and _then_ running `node_modules/.bin/next build` as you did above. This should persist the build file, which should get you past the "Cannot fine module" error and show the actual error that occurs during the build process. Can you try this, and let me know the result?

Well, that's unfortunate. The error is still not very clear after following those instructions.

```
# node_modules/.bin/next build:
Creating an optimized production build ...Killed
```

**Comment by checktheroads** [comment]
How long does the command run prior to erroring out like that? About the only time I've come across random explanation-less errors like that is during the favicon generation process, which can be a bit lengthy depending on the size of the icon. However, that situation specifically should produce a timeout error, so I doubt that's what you're seeing here.

Update: I just saw your edit with the kernel log - looks like a memory issue? How much to you have on the machine running the container? I'm also not very familiar with LXCs over Docker containers - I know hyperglass will work in Docker, as the CI build process runs through the entire installation & basic setup process on every commit.

**Comment by samip5** [comment]
> How long does the command run prior to erroring out like that? About the only time I've come across random explanation-less errors like that is during the favicon generation process, which can be a bit lengthy depending on the size of the icon. However, that situation specifically should produce a timeout error, so I doubt that's what you're seeing here.
>
> Update: I just saw your edit with the kernel log - looks like a memory issue? How much to you have on the machine running the container? I'm also not very familiar with LXCs over Docker containers - I know hyperglass will work in Docker, as the CI build process runs through the entire installation & basic setup process on every commit.

It happened to have only 2048MB so it error-ed pretty quickly, but upped it to 8096 and it was built pretty quickly.

**Comment by checktheroads** [comment]
Interesting. So going up to 8GB solved the issue then? I'll have to do some testing with varying amounts of RAM so I can recommend some basic system requirements in the docs.

**Comment by samip5** [comment]
> Interesting. So going up to 8GB solved the issue then? I'll have to do some testing with varying amounts of RAM so I can recommend some basic system requirements in the docs.

Yes, but I'm not entirely sure of how much RAM it required.

P.S Off-topic, does not belong in this issue, but: Why the target cannot be a DNS name when doing traceroute for example?
