### ISSUE TITLE
Github templates for issues

### ISSUE THREAD

**Issue by samip5** [checktheroads/hyperglass#52]
Why is there no templates to use, for like bug, feature request and suggestions?

There should be.

**Comment by checktheroads** [comment]
[There were, in the original branch](https://github.com/checktheroads/hyperglass/tree/v0/.github/ISSUE_TEMPLATE), however I planned to redo them once 1.0.0 is out of beta. That's still on the to-do list, unless you'd like to submit a PR to have it done sooner.
