### ISSUE TITLE
BGP ASpath for Junos returns "field required" error

### ISSUE THREAD

**Issue by brevius** [checktheroads/hyperglass#54]
The commands sent to router looks good:
`"show route protocol bgp table inet.0 aspath-regex ".* ASnum" detail | display xml"`
The XML output is returned from the router, but on the GUI the `"field required"` is shown. No other error is generated by hyperglass.
Tested JunOS version - 18.4R3

**Comment by checktheroads** [comment]
This should be fixed in 1.0.0-beta.50 - release published just a few minutes ago. Can you update and test again, please?

Thanks,
Matt

**Comment by brevius** [comment]
After upgrade to beta.50 no change. However I noticed the same problem with BGP route query. If the route is not found in the table the output is `The query completed, but no matching results were found.` But when the route exists `field required` is given back. RPC output looks good for all commands. 
Maybe I have to try with fresh install - not upgrade?

**Comment by checktheroads** [comment]
Is the XML output something you can share? I’m wondering if there’s something unique about one of the routes that requires an adjustment in the parser. If needed you can email it to [matt@hyperglass.io](mailto:matt@hyperglass.io)

**Comment by checktheroads** [comment]
Thanks for sending the XML - that helped me narrow this down. Looks like it was because the route had no communities at all, and Junos left the `communities` key out of the response entirely. This should be fixed in 1.0.0-beta.51, but let me know if not.

Thanks!
