### ISSUE TITLE
BGP queries for single hosts return incorrect results

### ISSUE THREAD

**Issue by forkwhilefork** [checktheroads/hyperglass#57]
# Bug Description
When a users runs a BGP query for a single host, e.g. 4.1.1.1, results may come back for many prefixes that do not contain that host.

# Expected behavior
I expect to see results for the exact set of prefixes which contain the host I queried for, which would be achieved (in my case, on junos) by the command `show route protocol bgp table inet.0 4.1.1.1 detail | display xml`.

# Steps to Reproduce
Submit a BGP Route query for 4.1.1.1. Note the responses include other prefixes which do not contain 4.1.1.1, but are contained by 4.0.0.0/9.

## Local Configurations
idk if it's relevant but here's my `devices.yaml`

```
---
# Credentials
credentials:
  - credential: &credential1
      username: *****
      password: *****

# Networks
networks:
  - network: &net_primary
      name: primary
      display_name: Main Network

# VRFs
vrfs:
  - &vrf_default
    name: default
    display_name: Global
    ipv4:
      access_list: &vrf_default_ipv4_acl
        - network: 10.0.0.0/8
          action: deny
        - network: 192.168.0.0/16
          action: deny
        - network: 172.16.0.0/12
          action: deny
        - network: 0.0.0.0/0
          action: permit
          ge: 8
          le: 24
    ipv6:
      access_list: &vrf_default_ipv6_acl
        - network: ::/0
          action: permit
          ge: 32
          le: 64

# Routers
routers:
  - name: cr2.lga6
    address: 10.x.x.x
    network: *net_primary
    credential: *credential1
    display_name: cr2.lga6
    port: 22
    nos: juniper
    vrfs:
      - <<: *vrf_default
        ipv4:
          source_address: x.x.x.x
          access_list: *vrf_default_ipv4_acl
        ipv6:
          source_address: x:x:x::x
          access_list: *vrf_default_ipv6_acl
    proxy: null
```

## Logs
Not an error, but this pretty clearly shows what's going on. For some reason we're asking whois for the containing block at the RIR level (which often has very little to do with internet routing) and then querying for that.
```
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:24 | _member_of ? Checking membership of 4.1.1.1/32 for 10.0.0.0/8
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:24 | _member_of ? Checking membership of 4.1.1.1/32 for 192.168.0.0/16
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:24 | _member_of ? Checking membership of 4.1.1.1/32 for 172.16.0.0/12
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:24 | _member_of ? Checking membership of 4.1.1.1/32 for 0.0.0.0/0
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:31 | _member_of ? 4.1.1.1/32 is a member of 0.0.0.0/0
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:109 | validate_ip ? 4.1.1.1/32 is allowed by access-list AccessList4(network=IPv4Network('0.0.0.0/0'), action='permit', ge=8, le=32)
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:145 | validate_ip ? Getting containing prefix for 4.1.1.1/32
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.external.bgptools:100 | run_whois_sync ? Opening connection to bgp.tools
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.external.bgptools:113 | run_whois_sync ? Closing connection to bgp.tools
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.external.bgptools:59 | parse_whois ? Parsed bgp.tools data: {'4.1.1.1': {'asn': '3356', 'ip': '4.1.1.1', 'prefix': '4.0.0.0/9', 'country': 'US', 'rir': 'ARIN', 'allocated': '2000-03-10', 'org': 'Level 3 Parent, LLC'}}
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.external.bgptools:199 | network_info_sync ? Cached network info for 4.1.1.1
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:162 | validate_ip ? Containing prefix: 4.0.0.0/9
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.models.validators:180 | validate_ip ? Validation passed for 4.1.1.1
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.routes:77 | query ? Initialized cache HyperglassCache(db=1, host=localhost, port=6379)
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.routes:86 | query ? Cache Timeout: 120
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.routes:103 | query ? No existing cache entry for query 456c104997684f941bcf9607ac0ea18cc83f3099ef3093989756073d88cfc00f
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.api.routes:105 | query ? Created new cache key 456c104997684f941bcf9607ac0ea18cc83f3099ef3093989756073d88cfc00f entry for query Query(query_location=cr2_lga6, query_type=bgp_route, query_vrf=default, query_target=4.0.0.0/9)
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.execution.construct:36 | __init__ ? Constructing bgp_route query for '4.0.0.0/9'
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.execution.construct:160 | queries ? Constructed query: ['show route protocol bgp table inet.0 4.0.0.0/9 detail | display xml']
Jul 15 23:23:12 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:12 | hyperglass.execution.execute:224 | scrape_direct ? Connecting directly to cr2_lga6...
Jul 15 23:23:16 ewr1lg01 hyperglass: [DEBUG] 20200715 23:23:16 | hyperglass.execution.execute:254 | scrape_direct ? Raw response for command "show route protocol bgp table inet.0 4.0.0.0/9 detail | display xml":

```

# Possible Solution
Skip the whois/bgp.tools lookup. Just query the router for what the user asked for. The router knows how to get the containing prefix from its RIB. OR, if you really want to get the containing prefix, add an `exact` to the query, so the results don't contain a bunch of prefixes that don't contain the IP the user asked for.

# Environment

## Server
 - OS: Centos 7
 - Python Version: 3.6.8
 - hyperglass Version: 1.0.0-beta.51

## Client
not relevant

**Comment by checktheroads** [comment]
I know this is buried in the docs, not well explained, and says RIPEStat and not bgp.tools, and for that I apologize. BUT, [you can disable this](https://hyperglass.io/docs/adding-devices#ipv4) with `force_cidr: false` under the VRF definition. While this is rarely if ever required for IPv4, it’s required on about half of the platforms I’ve come across for IPv6. Most platforms don’t allow doing a `show bgp` or equivalent for an IPv6 host route. So to keep feature parity between IP protocols, the default is to enable the containing prefix check for both. 

For the record, this feature does _not_ use whois data, I agree that that would be useless. bgp.tools uses _actual_ DFZ (granted, from their perspective) routes. Now, the fact that it’s returning 4.0.0.0/9 for 4.1.1.1 is odd, and I’m going to dig into that.

**Comment by forkwhilefork** [comment]
> I know this is buried in the docs, not well explained, and says RIPEStat and not bgp.tools, and for that I apologize. BUT, [you can disable this](https://hyperglass.io/docs/adding-devices#ipv4) with `force_cidr: false` under the VRF definition. While this is rarely if ever required for IPv4, it’s required on about half of the platforms I’ve come across for IPv6. Most platforms don’t allow doing a `show bgp` or equivalent for an IPv6 host route. So to keep feature parity between IP protocols, the default is to enable the containing prefix check for both. 
> 

Aha! Okay, I'll try that tomorrow and see if it works for v6 too.

> For the record, this feature does _not_ use whois data, I agree that that would be useless. bgp.tools uses _actual_ DFZ (granted, from their perspective) routes. Now, the fact that it’s returning 4.0.0.0/9 for 4.1.1.1 is odd, and I’m going to dig into that. 

The smallest covering prefix for 4.1.1.1 appears to be 4.0.0.0/9, so as far as I can see it's returning the right data. But there are other advertisements covered by that prefix as well. I think it might be best to add an `exact` when using the results of the bgp.tools lookup, to avoid this situation.

**Comment by forkwhilefork** [comment]
That solved the issue for v4, and didn't cause any problems for v6.

**Comment by checktheroads** [comment]
Yeah, Juniper allows IPv6 host queries, however Cisco IOS, NX-OS, and several others I can't remember off the top of my head do not. I'm going to close this issue out, but I've added an offline to-do to fix this section of the docs which I'll do on the next update.
