### ISSUE TITLE
Copied output from ping/traceroute escapes characters incorrectly

### ISSUE THREAD

**Issue by forkwhilefork** [checktheroads/hyperglass#59]
# Bug Description
When I run a ping/traceroute query and click the "Copy Output" button, the text that gets copied to my clipboard has escaped newlines (i.e. "\n") instead of the actual newline character, so it all appears on a single line. Also the whole string is in quotes.

# Expected behavior
The text copied to the clipboard should be the same as what appears on the page, as if I'd selected it and copied it manually.

# Steps to Reproduce
Run a ping or traceroute query and then click the "Copy Output" button.

## Local Configurations
I don't think this matters.

# Environment

## Server
 - OS: Centos 7
 - Python Version: 3.6.8
 - hyperglass Version: 1.0.0-beta.51

## Client
 - OS & Version: Windows 10 1909
 - Browser: Chrome 83.0.4103.116 and Firefox 78.0.2

**Comment by checktheroads** [comment]
I'm able to reproduce this and will fix this as soon as possible.

**Comment by checktheroads** [comment]
This is fixed in 1.0.0-beta.52
