### ISSUE TITLE
Copied output from BGP Route query appears as "[object Object]"

### ISSUE THREAD

**Issue by forkwhilefork** [checktheroads/hyperglass#61]
# Bug Description
When I run a ping/traceroute query and click the "Copy Output" button, the text that gets copied to my clipboard is "[object Object]" instead of the results of the query.

# Expected behavior
I expected to get something that at least kinda looks like the results of the query. I think a tab-separated table might be good?

# Steps to Reproduce
Run a BGP Route query and then click the "Copy Output" button.

## Local Configurations
I don't think this matters.

# Environment

## Server
 - OS: Centos 7
 - Python Version: 3.6.8
 - hyperglass Version: 1.0.0-beta.51

## Client
 - OS & Version: Windows 10 1909
 - Browser: Chrome 83.0.4103.116 and Firefox 78.0.2

**Comment by checktheroads** [comment]
This is with Juniper & table output, correct? I'm able to reproduce that on my system. I'll figure out a way to fix this.

**Comment by forkwhilefork** [comment]
Yes, correct. Thanks!
