### ISSUE TITLE
Centos install docs are missing a step

### ISSUE THREAD

**Issue by forkwhilefork** [checktheroads/hyperglass#62]
# Bug Description
In the Centos installation guide, there is a line `sudo yum -y install gcc-c++ make nodejs yarn redis`. However this will fail to install redis unless EPEL is installed. Without redis, hyperglass will not start. So, this should be added to the docs.

# Expected behavior
I would expect the instructions in the docs to work on a brand-new installation of Centos without any additional steps.

# Steps to Reproduce
Follow the instructions.

# Possible Solution
Add a line in the docs to install EPEL:
`yum -y install epel-release`

# Environment

## Server
 - OS: Centos 7

**Comment by forkwhilefork** [comment]
This isn't really a bug, but it's closer to a bug than a feature request I think.

**Comment by checktheroads** [comment]
Thank you! I've added this to the docs on my local repo, the next push will auto update the docs and close this out once it's live.

**Comment by forkwhilefork** [comment]
please see my comment on the commit - the installation of `epel-release` needs to happen _before_ the installation of `redis` so that the epel repo is in place and `redis` can be resolved.

**Comment by checktheroads** [comment]
Thanks - I moved it up to the initial steps along with the python install, so it would be there prior to running the Yarn/Redis/etc. installs.
