### ISSUE TITLE
[Agent API]: Key ingestion API failure

### ISSUE THREAD

**Issue by samip5** [checktheroads/hyperglass#67]
# Bug Description
Unable to setup agent as the key ingestion fails.

# Expected behavior
I expected it to add itself to hyperglass.

# Steps to Reproduce
1. Install Hyperglass-agent.
2. Run setup
3. Fail

# Environment

## Server

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.56** |
| **hyperglass Path** | `/home/users/samip537/hyperglass` |
| **Python Version** | `3.7.6` |
| **Platform Info** | `Linux-4.14.128-grsec-kapsi-x86_64-with-debian-8.11` |
| **CPU Info** | Intel Xeon E312xx (Sandy Bridge) |
| **Logical Cores** | `6` |
| **Physical Cores** | `3` |
| **Processor Speed** | 2.2999959999999997GHz |
| **Total Memory** | 16.8 GB |
| **Memory Utilization** | 20.1% |
| **Total Disk Space** | 24.99 GB |
| **Disk Utilization** | 29.4% |

 
# Related

https://github.com/checktheroads/hyperglass-agent/issues/7

**Comment by checktheroads** [comment]
Per my comment in checktheroads/hyperglass-agent#7, this should be resolved after an update to hyperglass-agent 0.1.6 and hyperglass 1.0.0-beta57, and please see the [Changelog](https://github.com/checktheroads/hyperglass/blob/v1.0.0/CHANGELOG.md) for details.

**Comment by checktheroads** [comment]
Closing, see #143
