### ISSUE TITLE
EdgeOS as a supported platform out of the box

### ISSUE THREAD

**Issue by samip5** [checktheroads/hyperglass#68]
# Feature Description
I would like to be able to just use device: edgeos without needing to manually specify the commands for it.

### Is your feature request related to a problem? Please describe.
Same thing that needed to be done for VyOS which basically means to add the default commands for it.

# Environment & Use Case
Using UBNT EdgeRouters in my environment.

**Comment by checktheroads** [comment]
Can you provide the commands you’re using in `commands.yaml` currently? I don’t have access to any UBNT devices to test the commands myself.

**Comment by samip5** [comment]
> Can you provide the commands you’re using in `commands.yaml` currently? I don’t have access to any UBNT devices to test the commands myself.

The issue is that I don't know the commands, but I can try with the VyOS ones if they are the same.

**Comment by checktheroads** [comment]
Closing this issue since neither of us have access to test EdgeOS devices.
