### ISSUE TITLE
Upgrade to latest build no longer runs any commands

### ISSUE THREAD

**Issue by astlaurent** [checktheroads/hyperglass#70]
Hello

Just upgraded a working build to the latest and it is throwing an internal server error when running any commands against any device.  Any ideas?

Log shows
Aug 10 08:07:38 hyperglass-prod hyperglass[32605]: File "/usr/local/lib/python3.6/site-packages/hyperglass/execution/main.py", line 36, in handler
Aug 10 08:07:38 hyperglass-prod hyperglass[32605]: raise DeviceTimeout(**exc_args)
Aug 10 08:07:38 hyperglass-prod hyperglass[32605]: hyperglass.exceptions.DeviceTimeout: Error connecting to ***-BRDR-01): Request timed out.

**Comment by checktheroads** [comment]
Hello, and sorry for the delay. Are you still having this problem? If so, can you share both your `hyperglass.yaml` and `devices.yaml`, as well as `/tmp/hyperglass.log`, obviously with any sensitive details removed. If needed you can send them to [matt@hyperglass.io](mailto:matt@hyperglass.io).

**Comment by astlaurent** [comment]
yes i am still having problems. I will send over the files
