### ISSUE TITLE
BGP map

### ISSUE THREAD

**Issue by TomHetmer** [checktheroads/hyperglass#72]
Hi,

have you thought about adding a bgp map-like feature?

It's a thing we like in [bird-lg](https://github.com/sileht/bird-lg), but there's a real issue with running so many full BGP sessions on some routers.

So it would be nice if you could query multiple devices directly and get the same output.

![image](https://user-images.githubusercontent.com/5316250/91173112-7d3a9500-e707-11ea-8f36-c9870b21b184.png)

**Comment by TomHetmer** [comment]
Btw - similar setup, but not open source http://bgpmap.sdv.fr/index.php?dst=1.1.1.1

It's something I'll have to write myself so I'm asking if hyperglass is interested in this/how hard it would be to implement in the current project

**Comment by checktheroads** [comment]
Hello,

Sorry for the delay! I can definitely see the value of this. That said, I’m not planning on adding any new features until 1.0.0 is out of beta as I want to get any major bugs and other in progress items shored up prior to introducing new factors. But I’ll leave this open as I don’t think it would be all that difficult to implement for any devices that support structured output (Juniper, at the moment, but FRR soon). 

Thanks,
Matt

**Comment by stv0g** [comment]
Just a few ideas for a browser based visualization of the BGP path:

- https://ialab.it.monash.edu/webcola/
- https://js.cytoscape.org/
- http://d3js.org/

The same kind of visualization could maybe also used for the traceroute results?

**Comment by checktheroads** [comment]
Because the front end is React, I'll likely be using a React-specific library for this. I did some searching around when this was opened and found [react-flow](https://github.com/wbkd/react-flow), which seemed to fit the bill.

I'm currently working on a refactor of the UI to TypeScript (in the ui-refactor branch), and I may work this into that either simultaneously or immediately after.

**Comment by checktheroads** [comment]
Hey @TomHetmer  & @stv0g, just wanted to let you know that this _is_ making it into the next beta release :) Preview below:

![](https://i.imgur.com/wtFFQv1.png)

The path shown is completely made up for testing purposes. I'm still tweaking the styles and stuff, but the nuts and bolts are there. Will close this out once that branch is merged and the release is available.
