### ISSUE TITLE
Bad Gateway error

### ISSUE THREAD

**Issue by harajukakei** [checktheroads/hyperglass#73]
Where should i start checking the issue with bad gateway ?
Already follow the documentation, buikd the ui, but whenever entering any command to the looking glass its only showing bad gateway.
Already turned on the debug and look for the logs, but nothing logged at the log files.

**Comment by makanbaks0** [comment]
I got this instead
`Internal Server Error`

I don't even know if hyperglass has been successfully ssh to device.
