### ISSUE TITLE
Leading and trailing whitespace of target input not removed

### ISSUE THREAD

**Issue by chriselsen** [checktheroads/hyperglass#75]
Leading and trailing whitespace of target input not removed

# Bug Description
For the free text input of the "target" input field, trailing or leading whitespace is not removed. This leads to error messages in subsequent steps. 

# Expected behavior
Remove any trailing or leading whitespace of the target input

# Steps to Reproduce
Enter the target input with a trailing (e.g. "8.8.8.8 ") or leading ( e.g. " 8.8.8.8") whitespace and select a corresponding query type.

## Local Configurations
N/A

## Logs
N/A

# Possible Solution
Use the https://docs.python.org/3/library/stdtypes.html#str.strip function to remove trailing and leading whitespace of the target input field. 

# Environment

## Server
N/A 

## Client
N/A

### Smartphone Details (if applicable)
N/A

**Comment by checktheroads** [comment]
Thanks for finding this - it will be fixed in the next release.
