### ISSUE TITLE
Target Validation: Subdomains with a hyphen aren't considered valid

### ISSUE THREAD

**Issue by HandyMenny** [checktheroads/hyperglass#77]
The regex used for target validation is defined here:
https://github.com/checktheroads/hyperglass/blob/c25cc5f3e13272b0534051e5a09614f852e2211c/hyperglass/ui/components/QueryTarget.js#L5

Example of domains that fails the validation:
- r3.sn-fpoq-o52l.googlevideo.com
- speedtest-mi1.cloudfire.it

I think the following regex should fix the bug:
`/^(?!:\/\/)([a-zA-Z0-9][a-zA-Z0-9-]+\.)?[a-zA-Z0-9][a-zA-Z0-9-]+\.[a-zA-Z]{2,6}?$/gim`

**Comment by checktheroads** [comment]
Good catch! This will be fixed in the next release.
