### ISSUE TITLE
Support for TNSR

### ISSUE THREAD

**Issue by ben-stratagem** [checktheroads/hyperglass#87]
I'd like to see support for [TNSR](https://www.tnsr.com) if possible and time can be found. Happy to assist with TNSR specific issues as have Hyperglass up & running and several TNSR routers.

**Comment by checktheroads** [comment]
I know TSNR runs FRR under the hood - are you able to install packages on it? If not, is there a rest API available? Barring those, we would need to establish which commands need to be run for BGP Route, AS path, community, ping, and traceroute (both in the default routing table and a VRF). If you’re able to determine all of those, I’d be happy to add native support.

Thanks!
Matt

**Comment by ben-stratagem** [comment]
Thanks for the swift reply Matt! 

TNSR runs on CentOS 8 so able to install packages. There is also a [REST API ](https://docs.netgate.com/tnsr/en/latest/api.html)
The way I envisaged it, which is likely wrong, would be SSH using a specific TNSR user, as this would take you directly to the TNSR shell with only the bare minimum commands permitted as configured by NACM, rather than CentOS then logging into either Vtysh or TNSR specifically. Happy to provide a list of the commands requested alternatively, let me know

Please let me know if you need any other info!

**Comment by checktheroads** [comment]
@ben-stratagem Added in 1.0.0-beta.63! Since Netgate recently allowed free use of TNSR for home use, I was able to obtain a copy. I tested as much as I could, please give it a go and let me know if any of the default commands need adjusting. You can see what those are [here](https://github.com/checktheroads/hyperglass/blob/v1.0.0/hyperglass/models/commands/tnsr.py).

**Comment by ben-stratagem** [comment]
Hey Matt!

Thanks for getting the TNSR support added so swiftly, smashing work. That all seems to be working after a smidge of tweaking – the default ping was only sending one, the waittime wasn’t being understood by TNSR CLI and the wait of 1 was being interpreted as send 1 ping. No huge deal as I adjusted and disabled some of the other commands anyway.

Thanks again, a very nice LG and one I’ll be recommending.

Cheers
