### ISSUE TITLE
docker run

### ISSUE THREAD

**Issue by kotviphp** [checktheroads/hyperglass#89]
![docker error](https://user-images.githubusercontent.com/25497579/95313268-c7d83100-08b1-11eb-9b84-6aa34ef75e10.JPG)

How dowload image ?

**Comment by checktheroads** [comment]
There is currently no direct support for Docker. That said...Docker is used in CI for testing, so you could look [here](https://github.com/checktheroads/hyperglass/blob/v1.0.0/.tests/app/ubuntu/Dockerfile) and implement your own Dockerfile based off of this.
