### ISSUE TITLE
hyperglass logo loads before logo in config

### ISSUE THREAD

**Issue by iamluca** [checktheroads/hyperglass#92]
# Bug Description
The fallback hyperglass logo & title of the site seems to be loading before the logo defined in the configuration file of hyperglass.

# Expected behavior
The expected behavior of it is to not show the hyperglass logo or title at the page at all and instead load the configuration logo.

# Steps to Reproduce
Simply put a new image in the configuration file and check it out.

## Local Configurations

```
<configs>
```

## Logs

```
<logs>
```

# Possible Solution

# Environment

## Client
 - OS & Version: 
 - Browser: 

### Smartphone Details (if applicable)
 - Device: 
 - OS: 
 - Browser:

**Comment by checktheroads** [comment]
This is fixed in v1.0.0-beta.65, which is currently being built in CI for release to PyPI. It should be available shortly.
